name: dynamic_theme_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.5.3

  cupertino_icons: ^1.0.8
  slang_build_runner: ^4.9.0
  slang: ^4.9.2
  slang_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: fonts/CormorantGaramond/CormorantGaramond-Light.ttf
          weight: 100
        - asset: fonts/CormorantGaramond/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: fonts/CormorantGaramond/CormorantGaramond-Medium.ttf
          weight: 500
        - asset: fonts/CormorantGaramond/CormorantGaramond-SemiBold.ttf
          weight: 600
        - asset: fonts/CormorantGaramond/CormorantGaramond-Bold.ttf
          weight: 700

    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope/Manrope-Bold.ttf
          weight: 700

    - family: Iceland
      fonts:
        - asset: fonts/Iceland/Iceland-Regular.ttf
          weight: 400
